name: Primer hello

on:
  push:
    branches:
    - dev
jobs:
  hello_word:
    runs-on: self-hosted
    steps:
    - name: Comienzan los RUN
      run: |
        echo "Hola mundo en mi propio runner" \
        echo "Ahora sale el echo con dos lineas"
    - run: date \ echo "<- Fecha"
