name: Primer hello

on:
  push:
    branches:
    - dev
jobs:
  hello_word:
    runs-on: self-hosted
    steps:
    - name: Echo del mensaje
      run: |
        echo "Hola mundo en mi propio runner"
        $time = date
        echoh $time
